
name: HTB Exam Status Daily Check

on:
  workflow_dispatch: {}
  schedule:
    # DST months: Mar->Oct run at 06:00 UTC (= 08:00 CEST)
    - cron: '0 6 * 3-10 *'
  push:
    branches:
      - main
    paths:
      - 'check_htb_exam.py'

permissions:
  contents: read

jobs:
  check-exam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List files (debug)
        run: |
          echo "Working directory: $(pwd)"
          echo "List repo root:"
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run HTB check script
        env:
          # optional: if you prefer to use a cookie for Academy access
          HTB_COOKIE_VALUE: ${{ secrets.HTB_COOKIE_VALUE }}
          # Mailgun configuration
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
          MAILGUN_FROM: ${{ secrets.MAILGUN_FROM }}
          # Choose exam: CBBH or CDSA
          HTB_EXAM: ${{ secrets.HTB_EXAM }}
        run: |
          python ./check_htb_exam.py
